[package]
name = "flint-formats"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"

ritoshark = { git = "https://github.com/RitoShark/RitoShark-Crates", rev = "8a4f03f", features = ["rman-verify"] }
ltk_inibin = { path = "../ltk_inibin", features = ["serde"] }
