/**
 * BnkPreview inline styles. Plain `React.CSSProperties` objects shared
 * across the panel - moving them here keeps the main component file
 * focused on logic and JSX.
 */
import type React from 'react';

// ---------------------------------------------------------------------------
// Inline styles
// ---------------------------------------------------------------------------

export const panelStyles: Record<string, React.CSSProperties> = {
    root: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        background: 'var(--bg-primary)',
        color: 'var(--text-primary)',
        overflow: 'hidden',
    },
    centered: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        gap: 8,
    },
    header: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: 12,
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '10px 14px',
        borderBottom: '1px solid var(--border)',
        background: 'var(--bg-secondary)',
    },
    summary: { display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
    badge: {
        fontSize: 11,
        fontWeight: 600,
        padding: '2px 8px',
        borderRadius: 4,
        background: 'color-mix(in srgb, var(--accent-primary) 15%, transparent)',
        color: 'var(--accent-primary)',
        letterSpacing: 0.5,
    },
    metaItem: { fontSize: 12, color: 'var(--text-primary)' },
    metaLabel: { color: 'var(--text-muted)', marginRight: 4 },
    controls: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
    modeGroup: { display: 'flex', gap: 4 },
    filterInput: {
        width: 130,
        padding: '4px 8px',
        fontSize: 12,
        background: 'var(--bg-primary)',
        color: 'var(--text-primary)',
        border: '1px solid var(--border)',
        borderRadius: 4,
        outline: 'none',
    },
    volumeWrap: { display: 'flex', alignItems: 'center', gap: 6, color: 'var(--text-muted)' },
    binBar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '6px 14px',
        borderBottom: '1px solid var(--border)',
        background: 'var(--bg-tertiary, var(--bg-secondary))',
        fontSize: 12,
        gap: 8,
    },
    binStatus: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', minWidth: 0 },
    sourceChip: { display: 'inline-flex', alignItems: 'center', gap: 6 },
    sourceLabel: { color: 'var(--accent-primary)', fontWeight: 500 },
    sourceSep: { color: 'var(--text-muted)', margin: '0 2px' },
    binPath: {
        fontFamily: 'var(--font-mono, monospace)',
        color: 'var(--text-primary)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        maxWidth: 240,
    },
    subtle: { color: 'var(--text-muted)', fontSize: 12 },
    editBar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '6px 14px',
        borderBottom: '1px solid var(--border)',
        background: 'var(--bg-secondary)',
        fontSize: 12,
    },
    errorBanner: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '6px 12px',
        background: 'rgba(239,68,68,0.1)',
        color: 'var(--text-error, #f87171)',
        fontSize: 12,
        borderBottom: '1px solid var(--border)',
    },
    listWrap: { flex: 1, overflow: 'auto' },
    empty: {
        textAlign: 'center',
        padding: 40,
        color: 'var(--text-muted)',
        fontSize: 13,
    },
    table: { width: '100%', borderCollapse: 'collapse', fontSize: 12, tableLayout: 'fixed' },
    th: {
        textAlign: 'left',
        padding: '8px 12px',
        borderBottom: '1px solid var(--border)',
        color: 'var(--text-muted)',
        fontWeight: 500,
        position: 'sticky',
        top: 0,
        background: 'var(--bg-secondary)',
        zIndex: 1,
    },
    tr: { cursor: 'pointer', transition: 'background 0.1s' },
    eventRow: {
        cursor: 'pointer',
        transition: 'background 0.1s',
        background: 'var(--bg-tertiary, rgba(255,255,255,0.02))',
    },
    sectionHeader: {
        background: 'var(--bg-tertiary, rgba(255,255,255,0.03))',
        textTransform: 'uppercase',
        fontSize: 10,
        letterSpacing: 1,
    },
    td: {
        padding: '6px 12px',
        borderBottom: '1px solid var(--border-subtle, rgba(255,255,255,0.04))',
        verticalAlign: 'middle',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    playBtn: {
        width: 26,
        height: 26,
        padding: 0,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'rgba(255,255,255,0.05)',
        border: '1px solid var(--border)',
        borderRadius: 4,
        color: 'var(--text-primary)',
        fontSize: 11,
        lineHeight: 1,
    },
    ctxMenu: {
        position: 'fixed',
        minWidth: 200,
        background: 'var(--bg-secondary)',
        border: '1px solid var(--border)',
        borderRadius: 6,
        boxShadow: '0 8px 24px rgba(0,0,0,0.4)',
        padding: '4px 0',
        zIndex: 1000,
        fontSize: 12,
    },
    modalOverlay: {
        position: 'fixed',
        inset: 0,
        background: 'rgba(0,0,0,0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1001,
    },
    modal: {
        background: 'var(--bg-secondary)',
        border: '1px solid var(--border)',
        borderRadius: 8,
        minWidth: 360,
        maxWidth: 440,
        boxShadow: '0 12px 32px rgba(0,0,0,0.5)',
    },
    modalHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '12px 16px',
        borderBottom: '1px solid var(--border)',
        fontSize: 13,
    },
    modalBody: {
        padding: '16px',
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
    },
    modalFooter: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: 8,
        padding: '10px 16px',
        borderTop: '1px solid var(--border)',
    },
};
